server:
  port: 8085
spring:
  application:
    name: TypeKardex

  r2dbc:
    url: r2dbc:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres
    username: postgres.syyjmpdsuuorxysggtsn
    password: cristhopersocalay2025